spring:
  application:
    name: banking-api

  datasource:
    url: jdbc:h2:mem:bankingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

banking:
  card-limits:
    daily-atm-max: 100000
    daily-pos-max: 200000
    daily-online-max: 150000
    monthly-total-max: 1000000

logging:
  level:
    root: INFO
    com.likhith.bankingapi: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [reqId=%X{requestId}] %msg%n"
